const express = require('express');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const initSqlJs = require('sql.js');
const path = require('path');
const app = express();
const dbPath = process.env.DB_FILE || path.join(__dirname, 'data/electricity.db');
require('fs').mkdirSync(path.dirname(dbPath), {recursive:true});
let db;
const ready = initSqlJs().then(SQL=>{
  db = require('fs').existsSync(dbPath) ? new SQL.Database(require('fs').readFileSync(dbPath)) : new SQL.Database();
  db.run(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS subscribers(id INTEGER PRIMARY KEY AUTOINCREMENT,account_no TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT,address TEXT,joined_on TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,initial_reading REAL NOT NULL DEFAULT 0,weekly_minimum REAL NOT NULL DEFAULT 25,opening_balance REAL NOT NULL DEFAULT 0,opening_balance_paid REAL NOT NULL DEFAULT 0,credit_balance REAL NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,subscriber_id INTEGER NOT NULL REFERENCES subscribers(id),period_start TEXT NOT NULL,period_end TEXT NOT NULL,previous_reading REAL NOT NULL,current_reading REAL NOT NULL,kwh REAL NOT NULL,rate REAL NOT NULL,amount REAL NOT NULL,paid INTEGER NOT NULL DEFAULT 0,paid_at TEXT,minimum_charge REAL NOT NULL DEFAULT 0,paid_amount REAL NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(subscriber_id,period_start,period_end));\n  CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,subscriber_id INTEGER NOT NULL REFERENCES subscribers(id),amount REAL NOT NULL,payment_date TEXT NOT NULL,opening_applied REAL NOT NULL DEFAULT 0,invoice_applied REAL NOT NULL DEFAULT 0,credit_created REAL NOT NULL DEFAULT 0,note TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);\n  CREATE TABLE IF NOT EXISTS payment_allocations(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_id INTEGER NOT NULL REFERENCES payments(id),invoice_id INTEGER NOT NULL REFERENCES invoices(id),amount REAL NOT NULL);
  INSERT OR IGNORE INTO settings(key,value) VALUES('current_rate','1.00');`);
  const subscriberColumns = all('PRAGMA table_info(subscribers)').map(column=>column.name);
  if(!subscriberColumns.includes('initial_reading')) db.run('ALTER TABLE subscribers ADD COLUMN initial_reading REAL NOT NULL DEFAULT 0');
  if(!subscriberColumns.includes('weekly_minimum')) db.run('ALTER TABLE subscribers ADD COLUMN weekly_minimum REAL NOT NULL DEFAULT 25');
  if(!subscriberColumns.includes('opening_balance')) db.run('ALTER TABLE subscribers ADD COLUMN opening_balance REAL NOT NULL DEFAULT 0');
  if(!subscriberColumns.includes('opening_balance_paid')) db.run('ALTER TABLE subscribers ADD COLUMN opening_balance_paid REAL NOT NULL DEFAULT 0');
  if(!subscriberColumns.includes('credit_balance')) db.run('ALTER TABLE subscribers ADD COLUMN credit_balance REAL NOT NULL DEFAULT 0');
  const invoiceColumns = all('PRAGMA table_info(invoices)').map(column=>column.name);
  if(!invoiceColumns.includes('minimum_charge')) db.run('ALTER TABLE invoices ADD COLUMN minimum_charge REAL NOT NULL DEFAULT 0');
  if(!invoiceColumns.includes('paid_amount')) db.run('ALTER TABLE invoices ADD COLUMN paid_amount REAL NOT NULL DEFAULT 0');\n  db.run('UPDATE invoices SET paid_amount=amount WHERE paid=1 AND paid_amount=0');
  persist();
  return db;
});
function persist(){require('fs').writeFileSync(dbPath,Buffer.from(db.export()))}
function all(sql,...params){const st=db.prepare(sql);st.bind(params);const out=[];while(st.step())out.push(st.getAsObject());st.free();return out}
function get(sql,...params){return all(sql,...params)[0]}
function run(sql,...params){db.run(sql,params);const lastID=db.exec('SELECT last_insert_rowid() AS id')[0]?.values[0][0];persist();return {lastID}}
app.set('trust proxy',1);
app.use(express.json());
app.use(session({secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:'auto',maxAge:7*24*60*60*1000}}));
app.use((req,res,next)=>ready.then(()=>next()).catch(next));
app.use('/api',(req,res,next)=>{if(req.path==='/health'||req.path.startsWith('/auth/'))return next();if(!req.session.userId)return res.status(401).json({error:'يرجى تسجيل الدخول'});next()});
app.use(express.static(path.join(__dirname,'public')));

app.get('/api/summary',(req,res)=>{const {from,to,subscriber,status}=req.query; let where='1=1',p=[];if(from){where+=' AND period_start>=?';p.push(from)}if(to){where+=' AND period_end<=?';p.push(to)}if(subscriber){where+=' AND subscriber_id=?';p.push(subscriber)}if(status==='paid')where+=' AND paid=1';if(status==='unpaid')where+=' AND paid=0';if(status==='due')where+=' AND paid=0 AND period_end<=date(\'now\')';const s=get(`SELECT COALESCE(SUM(kwh),0) kwh,COALESCE(SUM(amount),0) due,COALESCE(SUM(CASE WHEN paid_amount>0 THEN paid_amount ELSE CASE WHEN paid=1 THEN amount ELSE 0 END END),0) collected,COUNT(*) count, SUM(CASE WHEN paid=0 THEN 1 ELSE 0 END) unpaid FROM invoices WHERE ${where}`,...p);res.json(s)});
app.get('/api/health',(_,res)=>res.json({ok:true,database:'connected'}));
app.get('/api/auth/status',(req,res)=>res.json({configured:!!get('SELECT id FROM users LIMIT 1'),authenticated:!!req.session.userId,username:req.session.username||null}));
app.post('/api/auth/setup',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(get('SELECT id FROM users LIMIT 1'))return res.status(409).json({error:'تم إعداد حساب المدير مسبقاً'});if(username.length<3||password.length<8)return res.status(400).json({error:'اسم المستخدم 3 أحرف على الأقل وكلمة المرور 8 أحرف على الأقل'});try{const hash=await bcrypt.hash(password,12),user=run('INSERT INTO users(username,password_hash) VALUES(?,?)',username,hash);req.session.userId=user.lastID;req.session.username=username;res.status(201).json({ok:true,username})}catch(e){res.status(400).json({error:'تعذر إنشاء حساب المدير'})}});
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||''),user=get('SELECT * FROM users WHERE username=?',username);if(!user||!await bcrypt.compare(password,user.password_hash))return res.status(401).json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'});req.session.regenerate(err=>{if(err)return res.status(500).json({error:'تعذر بدء جلسة الدخول'});req.session.userId=user.id;req.session.username=user.username;res.json({ok:true,username:user.username})})});
app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>{res.clearCookie('connect.sid');res.json({ok:true})}));
app.get('/api/settings',(_,res)=>res.json({rate:Number(get("SELECT value FROM settings WHERE key='current_rate'").value)}));
app.put('/api/settings',(req,res)=>{const rate=Number(req.body.rate);if(!Number.isFinite(rate)||rate<0)return res.status(400).json({error:'السعر غير صحيح'});run("UPDATE settings SET value=? WHERE key='current_rate'",String(rate));res.json({rate})});
app.get('/api/subscribers',(req,res)=>res.json(all(`SELECT s.*,COUNT(i.id) invoices,COALESCE(SUM(CASE WHEN i.paid=0 THEN MAX(i.amount-i.paid_amount,0) ELSE 0 END),0)+MAX(s.opening_balance-s.opening_balance_paid,0)-MAX(s.credit_balance,0) balance,COALESCE(SUM(CASE WHEN i.paid=0 THEN MAX(i.amount-i.paid_amount,0) ELSE 0 END),0)+MAX(s.opening_balance-s.opening_balance_paid,0) amount_due,MAX(s.credit_balance,0) credit_balance,COALESCE((SELECT current_reading FROM invoices x WHERE x.subscriber_id=s.id ORDER BY x.period_end DESC,x.id DESC LIMIT 1),s.initial_reading) current_reading FROM subscribers s LEFT JOIN invoices i ON i.subscriber_id=s.id GROUP BY s.id ORDER BY s.id DESC`)));
app.post('/api/subscribers',(req,res)=>{const {account_no,name,phone,address,joined_on,initial_reading}=req.body;const initial=Number(initial_reading),weeklyMinimum=Number(req.body.weekly_minimum??25),openingBalance=Number(req.body.opening_balance??0);if(!account_no||!name||!joined_on||!Number.isFinite(initial)||initial<0||!Number.isFinite(weeklyMinimum)||weeklyMinimum<0||!Number.isFinite(openingBalance)||openingBalance<0)return res.status(400).json({error:'تحقق من بيانات المشترك والقراءة الابتدائية والحد الأدنى الأسبوعي'});try{const r=run('INSERT INTO subscribers(account_no,name,phone,address,joined_on,initial_reading,weekly_minimum,opening_balance) VALUES(?,?,?,?,?,?,?,?)',account_no,name,phone||'',address||'',joined_on,initial,weeklyMinimum,openingBalance);res.status(201).json({id:r.lastID})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'رقم الحساب مستخدم مسبقاً':'تعذر حفظ المشترك'})}});
app.put('/api/subscribers/:id',(req,res)=>{const {account_no,name,phone,address,joined_on,active}=req.body,weeklyMinimum=Number(req.body.weekly_minimum??get('SELECT weekly_minimum FROM subscribers WHERE id=?',req.params.id)?.weekly_minimum??25);if(!account_no||!name||!joined_on||!Number.isFinite(weeklyMinimum)||weeklyMinimum<0)return res.status(400).json({error:'تحقق من بيانات المشترك والحد الأدنى الأسبوعي'});try{run('UPDATE subscribers SET account_no=?,name=?,phone=?,address=?,joined_on=?,active=?,weekly_minimum=? WHERE id=?',account_no,name,phone||'',address||'',joined_on,(active===false||active===0||active==='0')?0:1,weeklyMinimum,req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/subscribers/:id',(req,res)=>{if(get('SELECT 1 FROM invoices WHERE subscriber_id=?',req.params.id))return res.status(409).json({error:'للمشترك فواتير؛ يمكن إيقاف الحساب بدلاً من حذفه'});run('DELETE FROM subscribers WHERE id=?',req.params.id);res.json({ok:true})});
app.get('/api/subscribers/:id/last-reading',(req,res)=>{const subscriber=get('SELECT id,initial_reading FROM subscribers WHERE id=?',req.params.id);if(!subscriber)return res.status(404).json({error:'المشترك غير موجود'});const latest=get('SELECT current_reading,period_end FROM invoices WHERE subscriber_id=? ORDER BY period_end DESC,id DESC LIMIT 1',req.params.id);res.json({reading:latest?Number(latest.current_reading):Number(subscriber.initial_reading),date:latest?.period_end||null,source:latest?'invoice':'initial'})});
app.get('/api/payments',(req,res)=>{let sql=`SELECT p.*,s.account_no,s.name FROM payments p JOIN subscribers s ON s.id=p.subscriber_id WHERE 1=1`,params=[];if(req.query.from){sql+=' AND p.payment_date>=?';params.push(req.query.from)}if(req.query.to){sql+=' AND p.payment_date<=?';params.push(req.query.to)}if(req.query.subscriber){sql+=' AND p.subscriber_id=?';params.push(req.query.subscriber)}sql+=' ORDER BY p.payment_date DESC,p.id DESC';res.json(all(sql,...params))});
app.post('/api/payments',(req,res)=>{const subscriberId=Number(req.body.subscriber_id),amount=Number(req.body.amount),paymentDate=String(req.body.payment_date||new Date().toISOString().slice(0,10)),note=String(req.body.note||'').trim(),subscriber=get('SELECT * FROM subscribers WHERE id=?',subscriberId);if(!subscriber)return res.status(400).json({error:'اختر مشتركاً صحيحاً'});if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'أدخل مبلغ دفعة أكبر من صفر'});if(!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate))return res.status(400).json({error:'تاريخ الدفعة غير صحيح'});try{const payment=run('INSERT INTO payments(subscriber_id,amount,payment_date,note) VALUES(?,?,?,?)',subscriberId,amount,paymentDate,note);let remaining=amount,openingApplied=0,invoiceApplied=0;const openingDue=Math.max(Number(subscriber.opening_balance||0)-Number(subscriber.opening_balance_paid||0),0);openingApplied=Math.min(remaining,openingDue);if(openingApplied>0){run('UPDATE subscribers SET opening_balance_paid=opening_balance_paid+? WHERE id=?',openingApplied,subscriberId);remaining-=openingApplied}const invoices=all('SELECT id,amount,paid_amount FROM invoices WHERE subscriber_id=? AND paid=0 ORDER BY period_end,id',subscriberId);for(const invoice of invoices){if(remaining<=0)break;const due=Math.max(Number(invoice.amount)-Number(invoice.paid_amount||0),0),applied=Math.min(remaining,due);if(applied<=0)continue;const paidAmount=Number(invoice.paid_amount||0)+applied,paid=paidAmount>=Number(invoice.amount)?1:0;run('INSERT INTO payment_allocations(payment_id,invoice_id,amount) VALUES(?,?,?)',payment.lastID,invoice.id,applied);run('UPDATE invoices SET paid_amount=?,paid=?,paid_at=? WHERE id=?',paidAmount,paid,paid?paymentDate:null,invoice.id);invoiceApplied+=applied;remaining-=applied}const creditCreated=+Math.max(remaining,0).toFixed(2);if(creditCreated>0)run('UPDATE subscribers SET credit_balance=credit_balance+? WHERE id=?',creditCreated,subscriberId);run('UPDATE payments SET opening_applied=?,invoice_applied=?,credit_created=? WHERE id=?',openingApplied,invoiceApplied,creditCreated,payment.lastID);res.status(201).json({id:payment.lastID,opening_applied:openingApplied,invoice_applied:invoiceApplied,credit_created:creditCreated})}catch(e){res.status(400).json({error:'تعذر تسجيل الدفعة: '+e.message})}});
app.get('/api/invoices',(req,res)=>{let sql=`SELECT i.*,MAX(i.amount-i.paid_amount,0) remaining,s.account_no,s.name,s.phone FROM invoices i JOIN subscribers s ON s.id=i.subscriber_id WHERE 1=1`,p=[];if(req.query.from){sql+=' AND i.period_start>=?';p.push(req.query.from)}if(req.query.to){sql+=' AND i.period_end<=?';p.push(req.query.to)}if(req.query.subscriber){sql+=' AND i.subscriber_id=?';p.push(req.query.subscriber)}if(req.query.status==='unpaid')sql+=' AND i.paid=0';if(req.query.status==='due')sql+=' AND i.paid=0 AND i.period_end<=date(\'now\')';if(req.query.status==='paid')sql+=' AND i.paid=1';sql+=' ORDER BY i.period_end DESC,i.id DESC';res.json(all(sql,...p))});
app.get('/api/reports/unpaid',(req,res)=>{if(req.query.status==='paid')return res.json([]);let where='i.paid=0',p=[];if(req.query.status==='due')where+=' AND i.period_end<=date(\'now\')';if(req.query.from){where+=' AND i.period_start>=?';p.push(req.query.from)}if(req.query.to){where+=' AND i.period_end<=?';p.push(req.query.to)}if(req.query.subscriber){where+=' AND s.id=?';p.push(req.query.subscriber)}res.json(all(`SELECT s.id,s.account_no,s.name,COUNT(i.id) unpaid_count,COALESCE(SUM(i.kwh),0) kwh,COALESCE(SUM(MAX(i.amount-i.paid_amount,0)),0) balance,MIN(i.period_start) earliest_period,MAX(i.period_end) latest_period FROM invoices i JOIN subscribers s ON s.id=i.subscriber_id WHERE ${where} GROUP BY s.id,s.account_no,s.name HAVING COUNT(i.id)>0 ORDER BY balance DESC`,...p))});
app.post('/api/invoices',(req,res)=>{const {subscriber_id,period_start,period_end,current_reading}=req.body;const cur=Number(current_reading);const submittedRate=req.body.rate===undefined||req.body.rate===''?Number(get("SELECT value FROM settings WHERE key='current_rate'").value):Number(req.body.rate);const subscriber=get('SELECT id,initial_reading,weekly_minimum,credit_balance FROM subscribers WHERE id=? AND active=1',subscriber_id);if(!subscriber)return res.status(400).json({error:'المشترك غير موجود أو غير نشط'});const latest=get('SELECT current_reading,period_end FROM invoices WHERE subscriber_id=? ORDER BY period_end DESC,id DESC LIMIT 1',subscriber_id);const prev=latest?Number(latest.current_reading):Number(subscriber.initial_reading);if(!period_start||!period_end||period_start>period_end)return res.status(400).json({error:'تحقق من بداية ونهاية الفترة'});if(latest&&period_start<=latest.period_end)return res.status(400).json({error:'بداية الفترة يجب أن تكون بعد آخر فترة مسجلة ('+latest.period_end+')'});if(!Number.isFinite(cur)||cur<prev)return res.status(400).json({error:'القراءة الحالية يجب ألا تقل عن آخر قراءة محفوظة ('+prev+')'});if(!Number.isFinite(submittedRate)||submittedRate<0)return res.status(400).json({error:'سعر الكيلو غير صحيح'});const kwh=cur-prev,rate=submittedRate,minimum=Number(subscriber.weekly_minimum??25),amount=+Math.max(kwh*rate,minimum).toFixed(2);try{const creditApplied=Math.min(Number(subscriber.credit_balance||0),amount),paidAmount=+creditApplied.toFixed(2),paid=paidAmount>=amount?1:0,paidAt=paid?new Date().toISOString().slice(0,10):null;const r=run('INSERT INTO invoices(subscriber_id,period_start,period_end,previous_reading,current_reading,kwh,rate,amount,minimum_charge,paid_amount,paid,paid_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',subscriber_id,period_start,period_end,prev,cur,kwh,rate,amount,minimum,paidAmount,paid,paidAt);if(creditApplied>0)run('UPDATE subscribers SET credit_balance=MAX(credit_balance-?,0) WHERE id=?',creditApplied,subscriber_id);run("UPDATE settings SET value=? WHERE key='current_rate'",String(rate));res.status(201).json({id:r.lastID,previous_reading:prev,kwh,rate,amount,minimum_charge:minimum,credit_applied:paidAmount})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'توجد فاتورة لهذه الفترة مسبقاً':'تعذر إنشاء الفاتورة'})}});
app.patch('/api/invoices/:id/payment',(req,res)=>{const inv=get('SELECT * FROM invoices WHERE id=?',req.params.id);if(!inv)return res.status(404).json({error:'الفاتورة غير موجودة'});const paid=!!req.body.paid;run('UPDATE invoices SET paid=?,paid_at=? WHERE id=?',paid?1:0,paid?(req.body.paid_at||new Date().toISOString().slice(0,10)):null,req.params.id);res.json({ok:true})});
app.delete('/api/invoices/:id',(req,res)=>{run('DELETE FROM invoices WHERE id=?',req.params.id);res.json({ok:true})});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`Electricity Billing running on ${port}`));
